name: Build my application

on: [push]

jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print current directory
        run: pwd
      - name: List files in directory
        run: ls